addons:
    sonarcloud:
        organization: "klogg"
        token:
            secure: "UGPUf5WDmYfjK0sWixEdXN65HHeQ8cBOKchqCq4UcbW/qMxfAgZBmGS8hjDbN09XiZejWxGn2kPlO8Xs/qFgK9jqqq2f5hVv9juw4ynRcx66/MRzrRzzCvhZDPT6c02WlnSORW7MNg4XSrSMH2U/E7P6fgZYHxwHEPr/J3Zbf/4IW5BL2d1P57YNdsMulA4xkK23Eeg+b1R7DATQ+8nY2KpdnJO8+ovLsqDWg1dEFAcw/DfXqgm4MDqDkrgwVWX84HF7Ov/vg5TGKFBZVTqjtBy7eQqQ+u+yuIwG14x2oKakPkMA6h0kRTq1cdBPHilxkjA8uUJnAE1hKpGgJZfDzgGJZ7yAFJ13lsdtxEc746mv6BHSAXaw5deNc59OhB606TRy+IhIJp1tvD692XijE/pkH0LcUd1NPG8NhXOYRZl7I5p/1jkuCSpzVmbLqTckTQhmaxL+4baKIV65/oGUnBDidTFlCx3OeW0AC2LqxzlCD4Qm5gE7DflDucfWP/Qg47qdCKcX5Huf+eRxXSeAtSPPU8qG/FP2qb9GFsWCtf0r31tN4PICLLVA7K36PWjIvJyk1iRz7r6Wf6MiFQa3tqH66Q2xBBGca78JSGWjzsOtrNWgdgHh74OiobtyqYrG7bX1fnWmwZGoODtv0pIdVjx0h5o9z6Y6xM7gTps0EEQ="

language: c

os:
   - linux

compiler: gcc

dist: bionic
sudo: required

before_install:
   - export KVER="5.3.0-1009-gcp"
   - export KSRC="/usr/src/linux-headers-$KVER"
   - sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-proposed restricted main multiverse universe' >> /etc/apt/sources.list.d/proposed-repositories.list"
   - sudo apt-get update
   - sudo apt-get install -y build-essential linux-headers-$KVER gcc-8
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 10
   - sudo update-alternatives --set gcc /usr/bin/gcc-8

script:
   - strace -f -E LD_DEBUG=all build-wrapper-linux-x86-64 --out-dir bw-output make
   - sonar-scanner
